import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vitepress'
import { withMermaid } from 'vitepress-plugin-mermaid'

// Sidebar fragment is regenerated by scripts/render-api-docs.py alongside
// the python-api markdown tree; loading the JSON at config-eval time
// keeps VitePress configuration framework-agnostic (no JSON import
// attribute, no Vite-side asset import) and means the same script
// owns both halves of the API-reference contract.
const apiSidebarPath = fileURLToPath(new URL('./api-sidebar.json', import.meta.url))
const apiSidebar = JSON.parse(readFileSync(apiSidebarPath, 'utf8')) as Array<{
  text: string
  collapsed?: boolean
  items: Array<{ text: string; link: string }>
}>

function normalizeBase(base?: string): string {
  if (!base || base === '/') {
    return '/'
  }

  return base.endsWith('/') ? base : `${base}/`
}

const docsBase = normalizeBase(process.env.DOCS_BASE || '/')
const editBranch = process.env.DOCS_EDIT_BRANCH || 'main'
const gaId = process.env.MEMPALACE_DOCS_GA_ID

export default withMermaid(
  defineConfig({
    title: 'MemPalace',
    description: 'Give your AI a memory. Local-first storage and retrieval for AI workflows, with benchmark results and MCP tooling.',
    base: docsBase,

    // Docstrings legitimately reference loopback addresses (Ollama at
    // localhost:11434, palace-daemon at disks.jphe.in:8085) that the
    // dead-link checker can't reach from CI. Allowlist the patterns we
    // know are intentional rather than disabling the check globally.
    ignoreDeadLinks: [
      /^https?:\/\/localhost(:\d+)?(\/.*)?$/,
      /^https?:\/\/127\.0\.0\.1(:\d+)?(\/.*)?$/,
      /^https?:\/\/0\.0\.0\.0(:\d+)?(\/.*)?$/,
      /^https?:\/\/[^/]*\.jphe\.in(:\d+)?(\/.*)?$/,
    ],

    head: [
      ['link', { rel: 'icon', href: `${docsBase}mempalace_logo.png` }],
      ['link', { rel: 'preconnect', href: 'https://api.fontshare.com' }],
      ['link', { href: 'https://api.fontshare.com/v2/css?f[]=neue-machina@300,400,500,700,800&f[]=satoshi@300,400,500,700&display=swap', rel: 'stylesheet' }],
      ['link', { rel: 'preconnect', href: 'https://fonts.googleapis.com' }],
      ['link', { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' }],
      ['link', { href: 'https://fonts.googleapis.com/css2?family=Onest:wght@300;400;500;600&family=JetBrains+Mono:wght@400;500&display=swap', rel: 'stylesheet' }],
      ['meta', { property: 'og:title', content: 'MemPalace — AI Memory System' }],
      ['meta', { property: 'og:description', content: '96.6% LongMemEval recall. Zero API calls. Local, free, open source.' }],
      ['meta', { property: 'og:image', content: `${docsBase}mempalace_logo.png` }],
      ...(gaId ? [
        ['script', { async: '', src: `https://www.googletagmanager.com/gtag/js?id=${encodeURIComponent(gaId)}` }],
        ['script', {}, `window.dataLayer = window.dataLayer || [];\nfunction gtag(){dataLayer.push(arguments);}\ngtag('js', new Date());\ngtag('config', ${JSON.stringify(gaId)});`],
      ] as const : []),
    ],

    themeConfig: {
      logo: '/mempalace_logo.png',
      siteTitle: 'MemPalace',

      nav: [
        { text: 'Guide', link: '/guide/getting-started' },
        { text: 'Concepts', link: '/concepts/the-palace' },
        { text: 'Reference', link: '/reference/cli' },
        {
          text: 'Fork',
          items: [
            { text: 'Architecture', link: 'https://github.com/techempower-org/mempalace/blob/main/docs/ARCHITECTURE.md' },
            { text: 'Ecosystem', link: 'https://github.com/techempower-org/mempalace/blob/main/docs/ECOSYSTEM.md' },
            { text: 'Bibliography', link: 'https://github.com/techempower-org/mempalace/blob/main/docs/BIBLIOGRAPHY.md' },
            { text: 'Research', link: 'https://github.com/techempower-org/mempalace/tree/main/docs/research' },
            { text: 'Fork Changelog', link: 'https://github.com/techempower-org/mempalace/blob/main/FORK_CHANGELOG.md' },
          ],
        },
      ],

      sidebar: {
        '/guide/': [
          {
            text: 'Guide',
            items: [
              { text: 'Getting Started', link: '/guide/getting-started' },
              { text: 'Mining Your Data', link: '/guide/mining' },
              { text: 'Searching Memories', link: '/guide/searching' },
              { text: 'MCP Integration', link: '/guide/mcp-integration' },
              { text: 'Claude Code Plugin', link: '/guide/claude-code' },
              { text: 'Claude Code Retention', link: '/guide/claude-code-retention' },
              { text: 'Gemini CLI', link: '/guide/gemini-cli' },
              { text: 'Antigravity Plugin', link: '/guide/antigravity' },
              { text: 'OpenClaw Skill', link: '/guide/openclaw' },
              { text: 'Local Models', link: '/guide/local-models' },
              { text: 'Auto-Save Hooks', link: '/guide/hooks' },
              { text: 'Cursor IDE Hooks', link: '/guide/cursor-hooks' },
              { text: 'Configuration', link: '/guide/configuration' },
              { text: 'Remote / Team Server', link: '/guide/remote-server' },
            ],
          },
        ],
        '/concepts/': [
          {
            text: 'Concepts',
            items: [
              { text: 'The Palace', link: '/concepts/the-palace' },
              { text: 'Memory Stack', link: '/concepts/memory-stack' },
              { text: 'AAAK Dialect', link: '/concepts/aaak-dialect' },
              { text: 'Knowledge Graph', link: '/concepts/knowledge-graph' },
              { text: 'Specialist Agents', link: '/concepts/agents' },
              { text: 'Contradiction Detection', link: '/concepts/contradiction-detection' },
            ],
          },
        ],
        '/reference/': [
          {
            text: 'Reference',
            items: [
              { text: 'CLI Commands', link: '/reference/cli' },
              { text: 'MCP Tools', link: '/reference/mcp-tools' },
              { text: 'Python API', link: '/reference/python-api' },
              { text: 'API Reference', link: '/reference/api-reference' },
              { text: 'Module Map', link: '/reference/modules' },
              { text: 'Benchmarks', link: '/reference/benchmarks' },
              { text: 'Contributing', link: '/reference/contributing' },
            ],
          },
          {
            text: 'Python API Reference',
            link: '/reference/python-api/',
            items: apiSidebar,
          },
        ],
      },

      socialLinks: [
        { icon: 'github', link: 'https://github.com/techempower-org/mempalace' },
        { icon: 'discord', link: 'https://discord.com/invite/ycTQQCu6kn' },
      ],

      search: {
        provider: 'local',
      },

      footer: {
        message: 'Released under the MIT License.',
        copyright: 'Copyright © 2026 MemPalace contributors',
      },

      editLink: {
        pattern: `https://github.com/techempower-org/mempalace/edit/${editBranch}/website/:path`,
        text: 'Edit this page on GitHub',
      },
    },

    mermaid: {
      theme: 'dark',
    },
  })
)
