#!/usr/bin/env python3
"""Render website/public/llms-full.txt from the project's key docs.

Concatenates README, ARCHITECTURE, ECOSYSTEM, and CLAUDE.md into one
plain-text file LLMs can ingest in a single fetch. Each section is
separated by a header divider that names the source file.

Usage::

    scripts/render-llms-full.py              # write the file
    scripts/render-llms-full.py --check      # exit 1 if it would change
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = REPO_ROOT / "website" / "public" / "llms-full.txt"

SOURCES = [
    ("README.md", "Overview, landscape comparison, fork-ahead state, installation"),
    ("docs/ARCHITECTURE.md", "Four-layer model, verbatim-vs-derivative thesis, design principles"),
    ("docs/ECOSYSTEM.md", "Peer builds, companion tools, evaluation frameworks, adjacent systems"),
    ("CLAUDE.md", "Mission, design principles, contributing guidelines, operational state"),
]

PREAMBLE = """\
# MemPalace (techempower-org fork) — full context for LLMs

> Concatenation of the project's primary docs, generated by
> `scripts/render-llms-full.py`. The concise routing manifest lives
> at `/llms.txt`. Source-of-truth is the upstream files in the repo —
> if this file drifts, re-run the script.

Files included, in order:

"""


def build() -> str:
    parts = [PREAMBLE]
    for path, blurb in SOURCES:
        parts.append(f"- `{path}` — {blurb}\n")
    parts.append("\n")

    for path, _ in SOURCES:
        full = REPO_ROOT / path
        if not full.exists():
            print(f"missing: {full}", file=sys.stderr)
            sys.exit(2)
        parts.append(f"\n---\n\n# === {path} ===\n\n")
        parts.append(full.read_text())
        if not parts[-1].endswith("\n"):
            parts.append("\n")

    return "".join(parts)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true", help="exit 1 if output would change")
    args = p.parse_args()

    rendered = build()

    if args.check:
        existing = OUTPUT.read_text() if OUTPUT.exists() else ""
        if existing != rendered:
            print(f"drift: {OUTPUT.relative_to(REPO_ROOT)} would change", file=sys.stderr)
            return 1
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered)
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(rendered)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
